name: pypiper_bowtie2_paired

pep_version: 2.0.0
sample_table: paired_sample_table.csv

looper:
  output_dir: "$PROCESSED/pep-pypiper/bioinformatic/bowtie2/paired"

sample_modifiers:
  append:
    pipeline_interfaces: ["$CODE/pep-pypiper/bioinformatic/sample_pipeline_interface.yaml"]
  derive:
    attributes: [read1, read2]
    sources:
      FQ1: $CODE/pep-pypiper/bioinformatic/examples/paired/{filename}_1.fq.gz
      FQ2: $CODE/pep-pypiper/bioinformatic/examples/paired/{filename}_2.fq.gz
  imply:
    - if: 
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then: 
        genome: hg38
