name: snakemake-line-count

pep_version: 2.0.0
sample_table: wc_sample_table.csv
output_dir: $HOME/pep-snakemake/simple/examples

sample_modifiers:
  derive:
    attributes: [filename]
    sources:
      F: $CODE/pep-snakemake/simple/examples/{sample_name}.txt
